name: Linux CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x.x'

    - name: Install PowerShell Core
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https software-properties-common
        wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Set up alias in .bashrc and run script
      shell: bash
      run: |
        echo "alias create-dotnet-app='pwsh -File ./CreateSolution.ps1'" >> ~/.bashrc
        source ~/.bashrc
        create-dotnet-app -solutionName "TestSolution" -dotnetVersion "net8.0" -language "C#" -presentationType "mvc"

    - name: Run tests
      run: |
        dotnet test ./test/TestSolution.UnitTest/TestSolution.UnitTest.csproj
